IsmSiteBundlePrefix:
    resource: "@IsmSiteBundle/Resources/config/routing/site.yml"
    prefix:   /

IsmSiteBundle_links:
    resource: "@IsmSiteBundle/Resources/config/routing/links.yml"
    prefix:   /links

IsmSiteBundle_roadmaps:
    resource: "@IsmSiteBundle/Resources/config/routing/roadmaps.yml"
    prefix:   /roadmaps
