parameters:
#    ism_site.example.class: Ism\SiteBundle\Example

services:
#    ism_site.example:
#        class: %ism_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
