parameters:
#    ism_comment.example.class: Ism\CommentBundle\Example

services:
#    ism_comment.example:
#        class: %ism_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
