article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IsmBlogBundle:Article:edit" }

article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IsmBlogBundle:Article:delete" }

article_show:
    pattern:   /{slug}
    defaults:  { _controller: IsmBlogBundle:Article:show }
