<?php

namespace Sdz\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinksRepository extends EntityRepository
{
}
