links_show:
    pattern:  /{id}/show
    defaults: { _controller: "IsmSiteBundle:Links:show" }

links_new:
    pattern:  /new
    defaults: { _controller: "IsmSiteBundle:Links:new" }

links_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IsmSiteBundle:Links:edit" }

links_update:
    pattern:  /{id}/update
    defaults: { _controller: "IsmSiteBundle:Links:update" }
    requirements: { _method: post|put }

links_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IsmSiteBundle:Links:delete" }
    requirements: { _method: post|delete|get }
