ismsite_home:
    pattern:  /
    defaults: { _controller: IsmSiteBundle:Site:index }

ismsite_contact:
    pattern:  /contact
    defaults: { _controller: IsmSiteBundle:Site:contact }

ismsite_roadmaps:
    pattern:  /roadmaps
    defaults: { _controller: IsmSiteBundle:Roadmaps:index }

ismsite_links:
    pattern: /links
    defaults: { _controller: "IsmSiteBundle:Links:index" }

