ismsite_home:
    pattern:  /
    defaults: { _controller: IsmSiteBundle:Site:index }

ismsite_contact:
    pattern:  /contact
    defaults: { _controller: IsmSiteBundle:Site:contact }

ismsite_lien:
    pattern:  /liens
    defaults: { _controller: IsmSiteBundle:Site:links }

ismsite_roadmap:
    pattern:  /roadmaps
    defaults: { _controller: IsmSiteBundle:Site:roadmap }
