imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "IsmSiteBundle", "IsmBlogBundle", "FOSCommentBundle" ]
    # java: %java_path%
    filters:
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # Ajouter cela si vous avez des tables non gérées par Doctrine dans votre bdd
        # (Si vous rencontrez une erreur obscure à propos du type ENUM)
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            uploadable: true

# Activation de l'extension Twig intl
services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

# FOS Configuration
fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall duquel on utilisera ces utilisateurs
    user_class:    Ism\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    group:
        group_class: Ism\UserBundle\Entity\Group

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Ism\CommentBundle\Entity\Comment
            thread: Ism\CommentBundle\Entity\Thread

# Ornicar\AksimetBundle
ornicar_akismet:
    api_key: %akismet_key%
    url:     %akismet_url%

# Sonata Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

sonata_admin:
    title:      ISM - Panneau d'administration
    dashboard:
        groups:
            Blog:
                items:
                    - ism.blog.admin.article
                    - ism.blog.admin.categorie
                    - ism.blog.admin.commentaire
                    - ism.blog.admin.competence
            Utilisateurs:
                items:
                    - ism.admin.user
            Mediateque:
                items:
                    - ism.blog.admin.image
