sdzuser_index:
    pattern:   /
    defaults:  { _controller: SdzUserBundle:User:index }

sdzuser_fiche_ajouter:
    pattern:   /fiche/ajouter
    defaults:  { _controller: SdzUserBundle:User:ajouter }

sdzuser_fiche_modifier:
    pattern:   /fiche/modifier/{id}
    defaults:  { _controller: SdzUserBundle:User:modifier }
    requirements:
        id:   \d+

sdzuser_fiche_supprimer:
    pattern:   /fiche/supprimer/{id}
    defaults:  { _controller: SdzUserBundle:User:supprimer }
    requirements:
        id:   \d+

sdzuser_fiche_voir:
    pattern:   /fiche/{id}
    defaults:  { _controller: SdzUserBundle:User:voir }
    requirements:
        id:   \d+
