sdzuser_index:
    pattern:   /
    defaults:  { _controller: SdzUserBundle:User:index }

sdzuser_fiche_ajouter:
    pattern:   /ajouter
    defaults:  { _controller: SdzUserBundle:User:ajouter }

sdzuser_fiche_modifier:
    pattern:   /modifier/{id}
    defaults:  { _controller: SdzUserBundle:User:modifier }
    requirements:
        id:   \d+

sdzuser_fiche_supprimer:
    pattern:   /supprimer/{id}
    defaults:  { _controller: SdzUserBundle:User:supprimer }
    requirements:
        id:   \d+

sdzuser_voir:
    pattern:   /{username}
    defaults:  { _controller: SdzUserBundle:User:voir }
