sdzuser_index:
    pattern:   /
    defaults:  { _controller: SdzUserBundle:User:index }

sdzuser_fiche_create:
    pattern:   /ajouter
    defaults:  { _controller: SdzUserBundle:User:ajouter }

sdzuser_fiche_view:
    pattern:   /voir
    defaults:  { _controller: SdzUserBundle:Blog:voir }
