parameters:
#    sdz_admin.example.class: Sdz\AdminBundle\Example

services:
#    sdz_admin.example:
#        class: %sdz_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    sdz.blog.admin.article:
        class: Sdz\AdminBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Articles }
        arguments: [null, Sdz\BlogBundle\Entity\Article, SdzAdminBundle:ArticleAdmin]

    sdz.blog.admin.categorie:
        class: Sdz\AdminBundle\Admin\CategorieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Categories }
        arguments: [null, Sdz\BlogBundle\Entity\Categorie, SdzAdminBundle:CategorieAdmin]

    sdz.blog.admin.commentaire:
        class: Sdz\AdminBundle\Admin\CommentaireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Commentaires }
        arguments: [null, Sdz\BlogBundle\Entity\Commentaire, SdzAdminBundle:CommentaireAdmin]

    sdz.blog.admin.competence:
        class: Sdz\AdminBundle\Admin\CompetenceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Competences }
        arguments: [null, Sdz\BlogBundle\Entity\Competence, SdzAdminBundle:CompetenceAdmin]

    sdz.blog.admin.image:
        class: Sdz\AdminBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Images }
        arguments: [null, Sdz\BlogBundle\Entity\Image, SdzAdminBundle:ImageAdmin]

    sdz.admin.user:
        class: Sdz\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sdzblog, label: Utilisateurs }
        arguments: [null, Sdz\UserBundle\Entity\User, SdzAdminBundle:UserAdmin]
