sdzsite_home:
    pattern:  /
    defaults: { _controller: SdzSiteBundle:Site:index }

sdzsite_contact:
    pattern:  /contact
    defaults: { _controller: SdzSiteBundle:Site:contact }

sdzsite_lien:
    pattern:  /liens
    defaults: { _controller: SdzSiteBundle:Site:links }

sdzsite_roadmap:
    pattern:  /roadmaps
    defaults: { _controller: SdzSiteBundle:Site:roadmap }
