ismblog:
    pattern:  /{page}
    defaults: { _controller: IsmBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+

ismblog_feed:
    pattern:   /feed.rss
    defaults:  { _controller: IsmBlogBundle:Blog:feed }

IsmBlogBundle_article:
    resource: "@IsmBlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

article_new:
    pattern:  /new
    defaults: { _controller: "IsmBlogBundle:Article:new" }
